### ISSUE TITLE
curl fails due to circular dependencies with clang on 10.6.8 (x86_64)

### ISSUE THREAD

**Issue by barracuda156** [kencu/SnowLeopardPorts#3]
I am setting up Macports on 10.6.8 x86_64, and bootstrapping Macports with curl ran into unexpected problem: the following ports call for each other and fail to install:

Error: The following dependencies were not installed because all of them have unmet dependencies (likely due to a dependency cycle): libpsl python39 clang-9.0 cmake curl libomp llvm-9.0
Error: Follow https://guide.macports.org/#project.tickets if you believe there is a bug.
Error: Processing of port curl failed

This was vanilla Macports with zero changes to config or portfiles.

**Comment by kencu** [comment]
fixed by macports
